Add `time_budget_s` parameter
ray-project/tune-sklearn pull request #134
Opened 2020-11-05 13:59 UTC by krfricke

This passes the `time_budget_s` parameter to `tune.run()`.

This also refactors parts of the base search `_format_results()` method to deal with missing values from trials (that e.g. have not been received due to early stopping/timeout).

2020-11-05 21:04 UTC, Yard1 requested changes
Looks good! Can we also get a test for random search? Just in case

2020-11-05 21:04 UTC, Yard1 commented on tune_sklearn/tune_search.py
> +            ``datetime.timedelta`` object.
We may want to expand this docstring to explain when exactly they are stopped - at the end of the trial, at the start, in the middle, etc.

2020-11-05 21:04 UTC, Yard1 commented on tune_sklearn/tune_search.py
> +        run_args = dict(
Great idea, been wanting to put the args in a dict myself at some point :+1:

2020-11-06 14:28 UTC, krfricke commented
Added!

2020-11-06 16:35 UTC, Yard1 approved these changes

2020-11-06 20:32 UTC, merged