Import `mlflow` integration from new `air.integrations` module
ray-project/tune-sklearn pull request #264
Opened 2023-05-24 23:42 UTC by justinvyu

Ray has some unit-tests depending on this package. The `ray.tune.integration` package is getting hard-deprecated in Ray 2.6, so this needs package needs to import from the new location at `ray.air.integrations` to unblock that.

In particular, it's this user guide doctest that would fail: https://docs.ray.io/en/latest/tune/examples/tune-sklearn.html

2023-05-25 00:09 UTC, Yard1 approved these changes

2023-05-25 00:09 UTC, Yard1 commented
Actually, can we have a try...except import here? @justinvyu

2023-05-25 00:09 UTC, Yard1 requested changes
see above

2023-05-25 00:57 UTC, justinvyu commented
I think the MLFlowLoggerCallback already try catches if mlflow is not installed.

2023-06-28 21:59 UTC, matthewdeng commented
@Yard1 by try/except do you mean something like:

> try import from air --> except import from tune

2023-06-28 22:44 UTC, justinvyu commented
No need to try catch since tune_sklearn depends on ray>=2.0, and the module was already moved to air.integrations at 2.0. Relaunching the CI, then we can merge after it passes.

2023-06-28 23:31 UTC, justinvyu commented
CI for latest Ray release is failing due to a fix that did not make the branch cut

CI for master is failing due to a similar issue as this flaky example on ray: https://github.com/ray-project/ray/issues/35428

2023-06-30 21:24 UTC, justinvyu commented
Passing with master wheel here: https://github.com/ray-project/tune-sklearn/actions/runs/5426940588/jobs/9869633497

2023-06-30 21:27 UTC, Yard1 approved these changes

2023-06-30 21:27 UTC, merged